plugins:
  git-legal:
    enabled: true
    config:
      allow_strong_copyleft: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
      channel: "beta"
  sonar-php:
    enabled: true
    