notifications:
  email:
    on_success: never
    on_failure: change

language: php
services:
  - mysql

env:
  global:
    - SNIFF=1
    - TEST=1

matrix:
  fast_finish: true
  include:
    - php: 8.0
      env: WP_VERSION=nightly
    - php: 8.0
      env: WP_VERSION=latest
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.4 # minimum requirements
      env: WP_VERSION=5.5 # minimum requirements
    - php: 5.4
      dist: precise
      env: WP_VERSION=4.9 LEGACY=1 SNIFF=0 TEST=0
  allow_failures:
    - env: WP_VERSION=nightly

cache:
  apt: false

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - if [[ "$LEGACY" == "1" ]]; then composer install --no-dev --prefer-source --no-interaction --ignore-platform-reqs ; fi # Ignore platform requirements to install on lower PHP version and check that execution indeed fails.
  - if [[ "$LEGACY" != "1" ]]; then composer install --prefer-source --no-interaction --ignore-platform-reqs ; fi # Ignore platform requirements to install on lower PHP version and check that execution indeed fails.

script:
  # Search for PHP syntax errors.
  - if [[ "$LEGACY" != "1" ]]; then find -L $TRAVIS_BUILD_DIR -path $TRAVIS_BUILD_DIR/vendor -prune -o -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l ; fi
  - if [[ "$LEGACY" == "1" ]]; then find $TRAVIS_BUILD_DIR -maxdepth 1 -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l ; fi
  # Run PHPCS.
  - if [[ "$SNIFF" == "1" ]]; then vendor/bin/phpcs $TRAVIS_BUILD_DIR ; fi
